# Tuxedo Link Configuration
# Copy this file to config.yaml and adjust settings

# Email provider configuration
email:
  provider: mailgun  # Options: mailgun, sendgrid
  from_name: "Tuxedo Link"
  from_email: "noreply@tuxedolink.com"

# Mailgun configuration
mailgun:
  domain: "sandboxfd631e04f8a941d5a5993a11227ea098.mailgun.org"  # Your Mailgun domain
  # API key from environment: MAILGUN_API_KEY

# SendGrid configuration (if using sendgrid provider)
sendgrid:
  # API key from environment: SENDGRID_API_KEY
  # kept for backwards compatibility

# Deployment configuration
deployment:
  mode: local  # Options: local, production
  
  local:
    db_path: "data/tuxedo_link.db"
    vectordb_path: "cat_vectorstore"
  
  production:
    db_path: "/data/tuxedo_link.db"
    vectordb_path: "/data/cat_vectorstore"

